### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by inftord**
yes
epic PR indeed

### CODE REVIEW

**Comment by OoLunar** [comment]
Remove the following commands:
- Antimeme
- Autoreact
- Lock
- Tempantimeme
- Templock
- Unantimeme

Rename:
- Reaction Roles -> Menu Roles

Checkmark:
- Flip
- GuildIcon
- Invite
- Member Count
- Profile Picture
- Raw
- Repository
- Role Info
- Server Info
- Support
- Time Of

**Comment by OoLunar** [comment]
Actually just compare the current public commands with <https://github.com/OoLunar/Tomoe/tree/rewrite/v5/everything/Tomoe/src/Commands>. The file names should be used instead of any aliased-command names (if any)

**Comment by inftord** [comment]
yes my lord and savior i will do this hard work :pleading_face:

**Comment by OoLunar** [comment]
Thanks for the PR! I appreciate you always helping me in the Discord.

**Pull request merged**
