### PR TITLE
fix lang %s

### PR DESCRIPTION
**Pull request by botoaca**
Your %s changed lmao

### CODE REVIEW

**Comment by OoLunar** [comment]
And it'll keep changing too. Maybe I should just remove that section entirely

**Comment by nocturnodev** [comment]
sounds like a good idea

**Comment by botoaca** [comment]
you should just not specify the percentages. do this instead:

# Tomoe is written in:
C# & Docker

**Review by OoLunar — CHANGES_REQUESTED** [review]
Instead of updating the percentages, could you just remove them entirely please?

**Pull request merged**
